const COMPANY_LOGOS: Record<string, string> = {
  Freshworks: "freshworks.png",
  "Wisdom AI": "wisdom_ai.png",
  Finbox: "finbox.png",
  HSBC: "hsbc.png",
  Adotco: "adotco.png",
  Quizizz: "quizizz.png",
  Bigbasket: "bigbasket.png",
  "Goldman Sachs": "goldman_sachs.png",
  "ZS Associates": "zs_associates.png",
  "Sambanova Systems": "sambanova_systems.png",
  BCG: "bcg.png",
  "Lucio AI": "lucio_ai.png",
  "Spectral insights": "spectral_insights.png",
  Smallcase: "smallcase.png",
  "Hashed Em": "hashed_em.png",
  Entalpic: "entalpic.png",
  Goodera: "goodera.png",
  Turno: "turno.png",
  Citi: "citi.png",
  "Elevation Capital": "elevation_capital.png",
  Aspire: "aspire.png",
  Ultrahuman: "ultrahuman.png",
  Cashfree: "cashfree.png",
  Zepto: "zepto.png",
  Janes: "janes.png",
  Glean: "glean.png",
  Google: "google.png",
  "Pocket FM": "pocket_fm.png",
  Uber: "uber.png",
  Atlassian: "atlassian.png",
  Flipkart: "flipkart.png",
  Semrush: "semrush.png",
  Emergent: "emergent.png",
  "Vector Consulting": "vector_consulting.png",
  Grab: "grab.png",
  Indegene: "indegene.png",
  Foxconn: "foxconn.png",
  "Bahwan Cybertek": "bahwan_cybertek.png",
  "Fintech Startup": "fintech_startup.png",
  ThoughtSpot: "thoughtspot.png",
  Razorpay: "razorpay.png",
  Pidilite: "pidilite.png",
  Amazon: "amazon.png",
  Nference: "nference.png",
  Livspace: "livspace.png",
  "Cigna Healthcare": "cigna_healthcare.png",
  "AB InBev": "ab_inbev.png",
  Nielsen: "nielsen.png",
  Maxval: "maxval.png",
  Wayfair: "wayfair.png",
  "Microsoft India": "microsoft_india.png",
  "Novo Nordisk": "novo_nordisk.png",
  Shopdeck: "shopdeck.png",
  "Applied Intuition": "applied_intuition.png",
  Meesho: "meesho.png",
  "Flash.co": "flash_co.png",
  Anyscale: "anyscale.png",
  "Blink Health": "blink_health.png",
  "Juniper Networks": "juniper_networks.png",
  SpotDraft: "spotdraft.png",
  E6Data: "e6data.png",
  Gameskraft: "gameskraft.png",
  "Optimo Capital": "optimo_capital.png",
  Abinbev: "abinbev.png",
  Dvsi: "dvsi.png",
  Groww: "groww.png",
  Udaan: "udaan.png",
  "Movado Group": "movado_group.png",
  "Publicis Sapient": "publicis_sapient.png",
  Rippling: "rippling.png",
  "The Thinkers": "the_thinkers.png",
  Navi: "navi.png",
  HFT: "hft.png",
  Salesforce: "salesforce.png",
  Cohesity: "cohesity.png",
  Npdi: "npdi.png",
  "Agilitas Sports": "agilitas_sports.png",
  Stripe: "stripe.png",
  Zamp: "zamp.png",
  "Fidelity International": "fidelity_international.png",
  Reach: "reach.png",
  "Capria Ventures": "capria_ventures.png",
  Vantiva: "vantiva.png",
  Microsoft: "microsoft.png",
  Accenture: "accenture.png",
  Zeta: "zeta.png",
  "Mercedes-Benz": "mercedes_benz.png",
  MIQ: "miq.png",
  "JP Morgan & Chase": "jp_morgan___chase.png",
  Delhivery: "delhivery.png",
  Swiggy: "swiggy.png",
  Narvar: "narvar.png",
  Azentio: "azentio.png",
  "Rystad Energy": "rystad_energy.png",
  Myntra: "myntra.png",
  Gojek: "gojek.png",
  PushOwl: "pushowl.png",
  Cognizant: "cognizant.png",
  "The Media Ant": "the_media_ant.png",
};

export function getCompanyLogo(companyName: string): string | undefined {
  const lower = companyName.toLowerCase();
  return Object.entries(COMPANY_LOGOS).find(([key]) =>
    lower.includes(key.toLowerCase())
  )?.[1];
}

