import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Flent",
  description: "Read our Privacy Policy to understand how we collect, use, and protect your personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-background pt-24 pb-12">
      <div className="container-large mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
        <div className="prose prose-lg dark:prose-invert max-w-none">
          <h1 className="text-3xl md:text-4xl font-bold text-center mb-8 uppercase font-zin">
            FLENT.IN PRIVACY POLICY
          </h1>

          <p className="mb-4">Thank you for using Flent.in!</p>

          <p className="mb-6">
            Flent.in, a product offering of Slaash Technologies Private Limited (hereinafter referred to as “<strong>Platform</strong>”, “<strong>We</strong>”, “<strong>Our</strong>” or “<strong>Us</strong>”), values the trust placed in Us by You and therefore, We strive to follow the reasonable standards of care to protect privacy of the Personal Data shared by You on the Platform with Us. We recognize Your expectations with regard to privacy, confidentiality and security of the Personal Data that resides with the Platform.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">1. Scope</h2>
          <div className="space-y-4">
            <p>
              1.1. This privacy policy (this “<strong>Privacy Policy</strong>”) of the Platform applies to all users and others who access or use the Platform and submit any data (hereinafter referred to as either “<strong>You</strong>” or “<strong>Your</strong>”). The Privacy Policy governs the privacy practices regarding the collection, use, disclosure, transfer, retention and safeguard of Your Personal Data by the Platform.
            </p>
            <p>
              1.2. Your clicking of the “<em>I accept</em>” button and submission of Personal Data or if you are a minor, the submission of your Personal Data either by your parents (or your guardian) or by you with the permission of your parents (or guardian) to the Platform will be deemed as your acceptance of this Privacy Policy.
            </p>
            <p>
              1.3. All capitalized terms that have not been expressly defined herein shall have the meaning ascribed to them under the ‘Terms of Use’. This Privacy Policy should be read in conjunction and together with the Terms of Use set out at 03/03/2023. For the purposes of this Privacy Policy, ‘Personal Data’ or ‘Data’ shall have the meaning ascribed to it under applicable laws in India, including without limitation The Digital Personal Data Protection Act 2023 (“<strong>DPDP Act</strong>”) and the Information Technology (Reasonable security practices and procedures and sensitive personal data or data) Rules, 2011, and shall be deemed to include Your Personal Data and Data as well as that of any minor under Your care to whom You have provided access to the Platform.
            </p>
            <p>
              1.4. This Privacy Policy and Terms of Use are an electronic record in terms of the IT Act 2000 and rules thereunder, and are published in accordance with the provisions of Rule 3 (1) of the of the Information Technology (Intermediary Guidelines and Digital media Ethics Code) Rules, 2021 and Rule 4(1) of the Information Technology (Reasonable security practices and procedures and sensitive personal data or data) Rules, 2011, which mandates for publishing of rules and regulations, privacy policy and terms of use for access or usage of Our Platform. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">2. Consent</h2>
          <div className="space-y-4">
            <p>
              2.1. You expressly understand, agree and acknowledge that Our collection, disclosure, transfer, storage and processing of Your Personal Data or Data is for a lawful purpose connected with a function or activity of the Platform. You further understand, agree and acknowledge that Your Personal Data or Data is considered necessary for Us to provide various services on the Platform to You and for Your usage of the Platform and other services provided by Us.
            </p>
            <p>
              2.2. You hereby consent to the collection, storage, use, disclosure, transfer and processing of the Personal Data or Data by Us for the purposes set out herein. By accessing the Platform or by availing the services offered by Us on the Platform, You have deemed to have given consent to collect, store, use, disclose, transfer and process Your Personal Data or Data in accordance with this Privacy Policy. You hereby agree to be bound by Platform and the services provided by Us. You are providing Your Personal Data or Data out of Your free will.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">3. Changes to the Privacy Policy:</h2>
          <p>
            3.1. This Privacy Policy is subject to change from time to time without any written notice to You. We reserve the right, at Our sole discretion, to modify the terms of this Privacy Policy from time to time (“<strong>Updated Terms</strong>”). The Updated Terms shall be effective immediately and shall supersede this Privacy Policy. Please check the “Last Updated” legend at the top of this page to see when this Privacy Policy was last revised. We will not be under any obligation to notify You of any changes to this Privacy Policy. You shall be solely responsible for reviewing the Privacy Policy from time to time for any modifications. Your continued use of the Platform after the Updated Terms has been published, will imply Your acceptance to such Updated Terms. You are encouraged to periodically visit this page to review the Privacy Policy and any changes made to it. We are obligated to protect Your Personal Data in accordance with applicable laws and regulations.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">4. Third Party Services:</h2>
          <p>
            4.1. Your mobile service provider, mobile operating system provider, third party Platforms including the Platforms pre-loaded on Your smart phones powered by Android platform or customized Android ROM (“Device”) or otherwise, social media platforms and websites that You access, and third party operators may also collect, use and share data about You and Your usage. We cannot control how these third parties collect, use, share or secure this data. For Data about third-party privacy practices, please consult their respective privacy policies.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">5. Sharing of Personal Data:</h2>
          <div className="space-y-4">
            <p>
              5.1. We may disclose, share, transfer or part with Your Personal Data to Our consultants, agents, third party service providers, partners, other agencies, investors which may be in other countries and jurisdictions across the world (“Third Parties”). You authorize Us to disclose, share, transfer or part with such Personal Data or Data with such entities. We may disclose, share and/or transfer such Data to Third Parties for the purpose stated in paragraph – 4 above including to provide You with access to the Platform or activity conducted by Us, to provide services and features that You may need on Our Platform, to comply with Our legal obligations, to enforce Our Terms of Use, to facilitate Our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities.
            </p>
            <p>
              5.2. You hereby provide Your express consent to Us for sharing Your Personal Data with the aforesaid Third Parties for Our legitimate business activities and for the purpose stated in paragraph-4 above. We may disclose Personal Data to Our affiliates when necessary to perform services on Our behalf or on Your behalf, to provide display advertising and promotional services, providing search results and links (including paid listings and links).
            </p>
            <p>
              5.3. We shall endeavour that the Third Parties to whom We may provide access to Your Personal Data or Data for the purposes set out herein are under a contractual obligation to protect Your Personal Data or Data in accordance with the same standard that We have agreed to be subjected to under this Privacy Policy.
            </p>
            <p>
              5.4. In the event of any requirement by court order, government or quasi-government agency to disclose Your Personal Data, We will disclose Data as may be legally required. We may also disclose Your Personal Data if We, in good faith, believe that such disclosure is reasonably necessary to respond to court orders, or other legal process.
            </p>
            <p>
              5.5. In the event the Platform is merged with, or acquired by, another company or its business or the Platform is transferred/sold to another company, or in case of re-organization or re-structuring of Our business, We and Our affiliates may disclose or transfer Your Personal Data, wholly or in part, to another business entity, and You consent to such disclosure or transfer.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">6. Purpose and Use of Personal Data:</h2>
          <div className="space-y-4">
            <p>
              6.1. We collect the Data directly provided by You (which may include Personal Data) through Your access or usage of the Platform and log data, data collected through cookies and other similar technologies. You agree that We may collect such Personal Data, whenever relevant, including when You access or use Our Platform, use Our services, interact with Us or at the time of Your registration on the Platform.
            </p>
            <p>
              6.2. We collect Personal Data or Data (a) in order to provide You with a safe, efficient and customized experience while You access or use Platform or avail services offered by Us; (b) to validate and help You to complete any transaction or provide any product/services You have requested or authorized; (c) to provide services, features and products You have requested or to meet Your requirements; (d) to measure Your interest in our services and to inform You about Our offers, products, services, updates or customize Your experience; (e) to detect and protect Us against error, fraud and other criminal activity, enforce our terms and conditions; (f) to promote and market Our products, services and features; and (g) to perform activities such as data analytics to improve Our products and services.
            </p>
          </div>

          <h3 className="text-xl font-bold mt-6 mb-3 font-zin">6.3. Data Provided by You</h3>
          <div className="space-y-4">
            <p>
              6.3.1. Personal Data may include details such as Your name, age, gender, contact data, Adhaar card and Pan card. Insofar as sensitive personal data or data is concerned, it will carry the meaning as defined in the Information Technology (Reasonable security practices and procedures and sensitive personal data or data) Rules, 2011, as amended from time to time.
            </p>
            <p>
              6.3.2. We may collect Personal Data such as Your name, mobile number, and email, when You use the Platform at the time of Your registration. We may also collect Data such as zip code, age, gender, occupation etc. We will not be liable for any actions, claims, costs, expenses or other liabilities in this respect.
            </p>
            <p>
              6.3.3. The Platform may include links to other websites/applications from third parties and other content that links to third party websites/applications. Such websites/ applications are governed by their respective privacy policies and terms of use, which are out of the Platform’s control. The collection and use of any Data You provide while using a third party website or Platform through the Platform is governed by the privacy policy of the operator of such website / application You are using or visiting. If You can't find the privacy policy of any of such websites/application via a link on the website’s homepage, You should contact the relevant website / application operator directly for more data in that respect. We are not responsible for third-party websites/application content or their privacy practices, and will not be liable for any actions, claims, costs, expenses or other liabilities that may arise as a consequence.
            </p>
            <p>
              6.3.4. Except as provided herein, We do not solicit any Personal Data about You. The authenticity of the Personal Data or Data provided by You shall not be Our responsibility, and We will not be liable for any actions, claims, costs, expenses or other liabilities that may arise as a consequence. Also, if You share any Data with us voluntarily, We will not be liable for any actions, claims, costs, expenses or other liabilities that may arise as a consequence of such any unauthorized use or misuse of such Data.
            </p>
          </div>

          <h3 className="text-xl font-bold mt-6 mb-3 font-zin">6.4. Inferred Data through Usage and Log Data</h3>
          <p>
            6.4.1. We may track certain Data about You based upon Your behaviour and usage of the Platform. We use this Data for conducting internal research on Our users' demographics, devices, interests, and behaviour to better understand, protect and serve Our users. This Data is compiled and analysed on an aggregated basis. This Data may include Your computer browser data. We may also collect Your Data to track users behaviour and preferences for internal analytics and research and targeting cohorts. We may also use Your Data : (i) to validate and process Your request for the services offered on the Platform ; (ii) to improve the quality of the Platform; (iii) to assist You to determine which services best meet Your needs; or (iv) to facilitate Our internal business operations, including the fulfilment of any legal and regulatory requirements; or (v) to provide You with recommendation about services You may be interested in, based on Your use of the Platform; or (vi) to provide You with marketing communications and advertising that the Platform believe may be of interest of You.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">7. Retention of Personal Data:</h2>
          <p>
            7.1. The Data so collected shall be retained only for a limited duration necessary to fulfil the purposes outlined herein unless a longer retention period is required or permitted by law and only for the purposes defined above. Once the purpose is achieved, all Personal Data may be deleted, however, in a safe and secure mode.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">8. Non-Personal Data:</h2>
          <div className="space-y-4">
            <p>
              8.1. Non-Personal Data (“<strong>NPD</strong>”) shall mean any data that does not personally identify You and may include unique system or hardware identifiers, system or Platform software, and peripherals.
            </p>
            <p>
              8.2. Any NPD, when clubbed with Personal Data to personally identify an individual shall be treated as Personal Data
            </p>
          </div>

          <h3 className="text-xl font-bold mt-6 mb-3 font-zin">8.3. The following is the manner in which We collect, use, share and retain NPI.</h3>
          <div className="space-y-4">
            <p>
              8.4.1. <strong>Collection</strong>:<br className="hidden md:block" />
              You agree that the Platform may collect diagnostic, technical, usage related data, for the usage purposes described below.
            </p>
            <p>
              8.4.2. <strong>Usage</strong>:<br className="hidden md:block" />
              The NPD is gathered periodically to provide and improve the Platform and services therein facilitate the provision of software updates, product support and other services to You (if any) and verify compliance with the terms of this Policy.
            </p>
            <p>
              8.4.3. <strong>Sharing</strong>:<br className="hidden md:block" />
              To enable the Platform partners and third party developers to improve their software, hardware and services designed for use of the Platform, We may also provide any such partner or third party developer with a subset of diagnostic data that is relevant to that partner’s or developer’s software, hardware and/or services, as long as the diagnostic data is in a form that does not personally identify You.
            </p>
            <p>
              8.4.4. <strong>Retention</strong>:<br className="hidden md:block" />
              The NPD so collected shall be retained only for a limited duration necessary to fulfil the purposes outlined herein unless a longer retention period is required or permitted by law and only for the purposes defined above. Once the purpose is achieved, all Data may be deleted, however, in a safe and secure mode.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">9. Location Services:</h2>
          <div className="space-y-4">
            <p>
              9.4. The Platform, its licensees and agents, may access, collect and analyse Your usage of the Platform and other data related to Your location on a regular basis through Bluetooth and Wi-Fi signals and other technologies and data for the performance of the services provided by the Platform and to help improve the design, functionality, performance, and content of the Platform. In order to collect geo-location data, the location settings must be enabled on Your device. Therefore, in some cases, the Platform may request that You enable the location settings.
            </p>
            <p>
              9.5. Except in cases where any specific services requested by You require or involve personal identification, the Platform collects location data anonymously and in a form that does not personally identify You. By using the Platform, You agree and consent to transmission, collection, maintenance, processing and use of Your location data and queries to provide and improve such services of the Platform.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">10. Cookies:</h2>
          <div className="space-y-4">
            <p>
              10.4. For providing the services on the Platform, We may use technologies such as cookies to provide users with tailored data upon each visit to Our Platform. A ‘cookie’ is a small piece of data stored by a web server on a web browser so it can be later read back from that browser. Cookies are useful for enabling the browser to remember Data specific to a given user. We place both permanent and temporary cookies in Your computer’s hard drive. Every time You access Our Platform, Our servers through cookies collect basic technical data such as Your domain name, the address of the last URL visited prior to clicking through to the Platform, and Your browser and operating system, etc. We may collect this data for statistical purposes or otherwise to find out how Our Platform is used and navigated, including the number of hits, the frequency and duration of visits, most popular session times. We may use this data to evaluate and improve Our Platform or services. The cookies do not contain any Personal Data. If You disable all cookies, You may not be able to take advantage of all the features of Our Platform.
            </p>
            <p>
              10.5. We may combine Your Personal Data or Data or other data collected from tracking technologies and aggregate it with data collected from other users using Our services to attempt to provide You with the Services and a better experience on the Platform.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">11. Access, Correction and Deletion:</h2>
          <div className="space-y-4">
            <p>
              11.4. We strive hard to keep its records updated and accurate with Your latest Data. You shall be responsible to ensure that the Data or data You provide from time to time is and shall be correct, current and updated and You have all the rights, permissions and consents to provide such Data or data.
            </p>
            <p>
              11.5. You will have the option to withdraw the consent given earlier or request for the deletion of Your Personal Data or Data. If You wish to withdraw Your consent or have the Personal Data or Data that You have provided to Us deleted, You can always do so by sending a request to us on the e-mail id provided at the bottom of this page. You may note that the withdrawal of consent or deletion of certain Personal Data may lead to cancellation of Your registration with Us and/or Your access to certain features of the services can be restricted and may also lead to complete cessation of Your access to Platform.
            </p>
            <p>
              11.6. You acknowledge and agree that You may receive certain notifications relating to the Platform and its products and services on Your Device or on Your registered contact. You agree that any communication so received by You from Us will not amount to spam, unsolicited communication or a violation of Your registration on the national do not call registry. At any given point of time, if you decide to not receive notification, you may turn off such notifications by contacting us on our support email.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">12. Security and Compliance with Laws:</h2>
          <div className="space-y-4">
            <p>
              12.4. The terms shall be governed and construed in accordance with the laws of India.
            </p>
            <p>
              12.5. We strive to protect Your Personal Data against unauthorized disclosure, misuse, unlawful use, modification, loss or destruction. We take all reasonable measures and precautions, per standard industry practices, to keep Your Personal Data confidential. We ensure compliance with all applicable laws.
            </p>
            <p>
              12.6. We use reasonable administrative, technical, physical and managerial measures to safeguard Your Personal Data against loss, theft and unauthorized access, use and modification as per law. Unfortunately, no measures can be guaranteed to provide 100% security. Accordingly, We cannot guarantee the security of Your Data. By continuing to access the Platform You are aware of such risk.
            </p>
          </div>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-zin">13. Queries and Complaints:</h2>
          <p className="mb-6">
            We are committed to protect Your Personal Data collected and processed by Us and look forward to Your continued support for the same. In case of any feedback or concern regarding protection of Your Personal Data, or any privacy-related feedback or concerns, you may contact:
          </p>

          <div className="mt-8 pt-8 border-t border-gray-200">
            <p><strong>Grievance Officer:</strong> Rishabh Agnihotri</p>
            <p><strong>Contact:</strong> <a href="mailto:hello@flent.in" className="text-blue-600 hover:underline">hello@flent.in</a></p>
            <p><strong>Corporate Office:</strong> WeWork Pavilion, 62/63 The Pavilion, Church Street, Bangalore, Karnataka 560001</p>
          </div>
        </div>
      </div>
    </main>
  );
}
