name = "posthog-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# Once you deploy, you can add your custom domain here or in the dashboard
# routes = [
# 	{ pattern = "ph.flent.in", custom_domain = true }
# ]
